"""
BharatCare AI Pro · Disease Database v2.0
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Static medical reference data for all 15 diseases.
Author: Deol Allwyn Samuel J B · VLSI · CIT · Afynix Digital
"""

DISEASE_INFO = {
    "dengue": {
        "full_name": "Dengue Fever", "category": "Vector-borne", "icd_code": "A90",
        "description": "Viral infection transmitted by Aedes mosquitoes, endemic in tropical regions of India.",
        "causes": ["Aedes aegypti mosquito bite", "DENV 1-4 serotypes", "Stagnant water breeding grounds"],
        "symptoms": ["High fever (104°F+)", "Severe headache", "Pain behind the eyes", "Joint and muscle pain",
                     "Skin rash", "Nausea/vomiting", "Fatigue", "Mild bleeding (gums/nose)"],
        "complications": ["Dengue Hemorrhagic Fever", "Dengue Shock Syndrome", "Organ failure", "Thrombocytopenia"],
        "treatment": "Supportive: fluids, paracetamol, rest. No antivirals. Avoid NSAIDs.",
        "prevention": ["Eliminate stagnant water", "Use mosquito nets", "Wear full-sleeve clothing",
                       "Use repellents", "Dengvaxia vaccine (select cases)"],
        "incubation_days": "4–10 days", "contagious": False,
        "govt_helpline": "National Vector Borne Disease Control: 011-23061356",
    },
    "malaria": {
        "full_name": "Malaria", "category": "Vector-borne", "icd_code": "B54",
        "description": "Parasitic infection from Plasmodium species via Anopheles mosquito bites.",
        "causes": ["Plasmodium falciparum (severe)", "Plasmodium vivax (relapsing)", "Anopheles mosquito bite"],
        "symptoms": ["Cyclical fever with chills", "Sweating episodes", "Headache", "Nausea", "Vomiting",
                     "Muscle aches", "Anaemia", "Jaundice in severe cases"],
        "complications": ["Cerebral malaria", "Severe anaemia", "Acute respiratory distress", "Organ failure"],
        "treatment": "ACT (Artemisinin combination therapy), Chloroquine for P. vivax, Primaquine for relapse prevention.",
        "prevention": ["Insecticide-treated nets", "Indoor residual spraying", "Chemoprophylaxis for travellers",
                       "Eliminate breeding sites", "Protective clothing"],
        "incubation_days": "7–30 days", "contagious": False,
        "govt_helpline": "NVBDCP Malaria: 011-23736471",
    },
    "typhoid": {
        "full_name": "Typhoid Fever", "category": "Bacterial", "icd_code": "A01.0",
        "description": "Systemic infection caused by Salmonella typhi via contaminated food/water.",
        "causes": ["Salmonella typhi bacteria", "Contaminated water/food", "Poor sanitation", "Fecal-oral route"],
        "symptoms": ["Sustained high fever (103–104°F)", "Abdominal pain", "Headache", "Constipation or diarrhea",
                     "Rose-colored spots on trunk", "Weakness", "Loss of appetite", "Coated tongue"],
        "complications": ["Intestinal perforation", "Internal bleeding", "Encephalopathy", "Hepatitis"],
        "treatment": "Ciprofloxacin or Ceftriaxone (antibiotic). Azithromycin for uncomplicated cases.",
        "prevention": ["Clean drinking water (boil/filter)", "Typhoid vaccine (Vi-PS or Ty21a)",
                       "Proper hand hygiene", "Safe food handling"],
        "incubation_days": "6–30 days", "contagious": True,
        "govt_helpline": "IDSP Helpline: 11-23978046",
    },
    "pneumonia": {
        "full_name": "Pneumonia", "category": "Respiratory", "icd_code": "J18",
        "description": "Lung infection causing air sacs to fill with fluid/pus. Major cause of child mortality in India.",
        "causes": ["Streptococcus pneumoniae (most common)", "Influenza virus", "Respiratory syncytial virus",
                   "Klebsiella, Staphylococcus", "Aspiration"],
        "symptoms": ["Chest pain on breathing", "Shortness of breath", "Productive cough with phlegm",
                     "High fever with chills", "Fatigue", "Rapid breathing", "Confusion (elderly)"],
        "complications": ["Bacteremia/sepsis", "Pleural effusion", "Lung abscess", "Respiratory failure"],
        "treatment": "Antibiotics (Amoxicillin first-line), oxygen therapy, fluids. ICU for severe cases.",
        "prevention": ["Pneumococcal vaccine (PCV13)", "Influenza vaccine annually", "No smoking",
                       "Good hygiene", "Timely treatment of respiratory infections"],
        "incubation_days": "1–3 days", "contagious": True,
        "govt_helpline": "Respiratory helpline: 1800-11-4499",
    },
    "tuberculosis": {
        "full_name": "Tuberculosis (TB)", "category": "Bacterial", "icd_code": "A15",
        "description": "Mycobacterium tuberculosis infection. India has world's highest TB burden (2.8 million cases/year).",
        "causes": ["Mycobacterium tuberculosis", "Airborne transmission", "Close contact with TB patient",
                   "Malnutrition and weak immunity", "HIV co-infection"],
        "symptoms": ["Persistent cough (>2 weeks)", "Blood in sputum", "Night sweats", "Weight loss",
                     "Fatigue", "Chest pain", "Low-grade fever", "Loss of appetite"],
        "complications": ["Drug-resistant TB (MDR/XDR)", "Miliary TB", "TB meningitis", "Destroyed lung tissue"],
        "treatment": "DOTS (6-month RHEZ regimen). Nikshay portal registration mandatory in India.",
        "prevention": ["BCG vaccine at birth", "Early case detection", "Completing full treatment",
                       "Adequate nutrition", "Ventilated living spaces"],
        "incubation_days": "2–12 weeks (latent TB can reactivate years later)", "contagious": True,
        "govt_helpline": "Nikshay TB Helpline: 1800-11-6666",
    },
    "diabetes": {
        "full_name": "Diabetes Mellitus", "category": "Metabolic", "icd_code": "E11",
        "description": "Chronic metabolic disorder with insulin deficiency/resistance. India is 'Diabetes Capital' — 77 million affected.",
        "causes": ["Insulin resistance (Type 2)", "Autoimmune destruction of beta cells (Type 1)",
                   "Genetic predisposition", "Obesity", "Sedentary lifestyle", "Unhealthy diet"],
        "symptoms": ["Frequent urination (polyuria)", "Excessive thirst (polydipsia)", "Unexplained weight loss",
                     "Fatigue", "Blurred vision", "Slow wound healing", "Tingling in hands/feet"],
        "complications": ["Diabetic neuropathy", "Retinopathy (blindness)", "Nephropathy (kidney failure)",
                          "Cardiovascular disease", "Diabetic foot (amputation risk)"],
        "treatment": "Type 2: Metformin, lifestyle change. Type 1: Insulin. Monitor HbA1c every 3 months.",
        "prevention": ["Maintain healthy weight", "Regular physical activity (150 min/week)",
                       "Balanced diet (low GI foods)", "Avoid sugary drinks", "Regular screening after 40"],
        "incubation_days": "Chronic — develops over years", "contagious": False,
        "govt_helpline": "NPCDCS: 1800-11-4000",
    },
    "hypertension": {
        "full_name": "Hypertension (High BP)", "category": "Cardiovascular", "icd_code": "I10",
        "description": "Persistent BP ≥130/80 mmHg. 'Silent killer' — 220 million Indians have hypertension.",
        "causes": ["Genetic factors", "High sodium diet", "Obesity", "Sedentary lifestyle",
                   "Stress", "Alcohol/smoking", "Kidney disease", "Hormonal disorders"],
        "symptoms": ["Often asymptomatic", "Headache (morning)", "Dizziness", "Palpitations",
                     "Nosebleeds", "Visual disturbances", "Chest pain (crisis)"],
        "complications": ["Heart attack", "Stroke", "Heart failure", "Kidney damage", "Aortic aneurysm"],
        "treatment": "Lifestyle changes + antihypertensives (Amlodipine, Losartan, Atenolol). Target <130/80.",
        "prevention": ["Low salt diet (<5g/day)", "DASH diet", "Regular exercise",
                       "Limit alcohol", "Quit smoking", "Stress management", "Regular BP monitoring"],
        "incubation_days": "Chronic — develops over years", "contagious": False,
        "govt_helpline": "Heart helpline: 1800-11-4477",
    },
    "covid19": {
        "full_name": "COVID-19 (SARS-CoV-2)", "category": "Viral Respiratory", "icd_code": "U07.1",
        "description": "Respiratory illness caused by SARS-CoV-2 coronavirus. Pandemic disease, still circulating.",
        "causes": ["SARS-CoV-2 virus", "Respiratory droplets", "Aerosol transmission", "Surface contact (less common)"],
        "symptoms": ["Fever", "Dry cough", "Fatigue", "Loss of smell (anosmia)", "Loss of taste",
                     "Shortness of breath", "Body aches", "Sore throat", "Diarrhea"],
        "complications": ["Severe pneumonia", "ARDS", "Long COVID", "Blood clots", "Multi-organ failure"],
        "treatment": "Supportive care. Antiviral (Paxlovid/Molnupiravir) for high-risk. Steroids for severe cases.",
        "prevention": ["COVID-19 vaccination", "Masks in crowded areas", "Hand hygiene",
                       "Ventilation", "Isolation when symptomatic"],
        "incubation_days": "2–14 days", "contagious": True,
        "govt_helpline": "COVID-19 Helpline: 1075",
    },
    "cholera": {
        "full_name": "Cholera", "category": "Bacterial", "icd_code": "A00",
        "description": "Acute diarrheal infection from Vibrio cholerae via contaminated water. Can kill within hours.",
        "causes": ["Vibrio cholerae O1/O139", "Contaminated water/food", "Poor sanitation", "Fecal-oral route"],
        "symptoms": ["Profuse watery diarrhea (rice-water stools)", "Vomiting", "Severe dehydration",
                     "Muscle cramps", "Rapid heart rate", "Sunken eyes", "Dry mouth", "Low blood pressure"],
        "complications": ["Severe dehydration (shock)", "Electrolyte imbalance", "Kidney failure", "Death (untreated)"],
        "treatment": "ORS immediately. IV fluids for severe cases. Doxycycline/Azithromycin antibiotic.",
        "prevention": ["Safe water (boil/chlorinate)", "Oral Cholera Vaccine (OCV)",
                       "Proper sewage disposal", "Food safety", "Hand washing with soap"],
        "incubation_days": "2 hours–5 days", "contagious": True,
        "govt_helpline": "IDSP Outbreak: 11-23978046",
    },
    "hepatitis": {
        "full_name": "Viral Hepatitis", "category": "Viral", "icd_code": "B19",
        "description": "Liver inflammation from hepatitis viruses. Hep B/C are major causes of liver cirrhosis in India.",
        "causes": ["Hepatitis A/E (fecal-oral)", "Hepatitis B (blood/sexual)", "Hepatitis C (blood)",
                   "Contaminated needles", "Mother-to-child transmission (Hep B)"],
        "symptoms": ["Jaundice (yellow skin/eyes)", "Abdominal pain (right upper)", "Fatigue", "Nausea",
                     "Dark urine", "Pale-coloured stools", "Loss of appetite", "Low-grade fever"],
        "complications": ["Liver cirrhosis", "Liver failure", "Hepatocellular carcinoma", "Coagulopathy"],
        "treatment": "Hep A/E: supportive. Hep B: Tenofovir/Entecavir. Hep C: DAAs (>95% cure rate).",
        "prevention": ["Hepatitis B vaccine (universal at birth in India)", "Safe injection practices",
                       "Safe sex", "Blood screening", "Clean water (Hep A/E)"],
        "incubation_days": "15–180 days (varies by type)", "contagious": True,
        "govt_helpline": "NVHCP: 011-23731748",
    },
    "chickenpox": {
        "full_name": "Chickenpox (Varicella)", "category": "Viral", "icd_code": "B01",
        "description": "Highly contagious viral infection with itchy blister rash. Caused by Varicella Zoster Virus.",
        "causes": ["Varicella-Zoster Virus (VZV)", "Airborne droplets", "Direct contact with blisters"],
        "symptoms": ["Itchy blistering rash", "Fluid-filled vesicles", "Low-grade fever", "Fatigue",
                     "Headache", "Loss of appetite", "Runny nose", "Rash on scalp/face/trunk first"],
        "complications": ["Secondary bacterial infections", "Pneumonia", "Encephalitis", "Reactivation as shingles (adults)"],
        "treatment": "Symptomatic: antihistamines, calamine lotion, paracetamol. Acyclovir for immunocompromised.",
        "prevention": ["Varicella vaccine (2 doses)", "Isolation of infected persons", "Avoid scratching blisters"],
        "incubation_days": "10–21 days", "contagious": True,
        "govt_helpline": "Immunisation helpline: 1800-11-4449",
    },
    "conjunctivitis": {
        "full_name": "Conjunctivitis (Pink Eye)", "category": "Ocular", "icd_code": "H10",
        "description": "Inflammation of conjunctiva. Very common in India especially during monsoon season.",
        "causes": ["Bacterial (Staphylococcus, Streptococcus)", "Viral (Adenovirus — highly contagious)",
                   "Allergic (dust, pollen)", "Chemical exposure"],
        "symptoms": ["Red eyes", "Discharge (watery/purulent)", "Itching and burning", "Excessive tearing",
                     "Swollen eyelids", "Sensitivity to light", "Crusting on eyelashes in morning"],
        "complications": ["Corneal ulceration (rare)", "Vision impairment (untreated)", "Spread to others"],
        "treatment": "Bacterial: antibiotic eye drops (Ciprofloxacin). Viral: artificial tears, cold compress. Allergic: antihistamine drops.",
        "prevention": ["Hand washing", "Don't share towels/pillows", "Avoid touching eyes",
                       "Sunglasses outdoors", "Treating underlying allergy"],
        "incubation_days": "1–3 days (viral/bacterial)", "contagious": True,
        "govt_helpline": "Eye health: 1800-11-4445",
    },
    "anaemia": {
        "full_name": "Anaemia", "category": "Blood Disorder", "icd_code": "D64",
        "description": "Haemoglobin below normal levels. India has one of world's highest anaemia burdens — 53% of women affected.",
        "causes": ["Iron deficiency (most common)", "Vitamin B12/folate deficiency", "Thalassaemia",
                   "Chronic disease", "Blood loss (menstruation)", "Malnutrition", "Hookworm"],
        "symptoms": ["Fatigue and weakness", "Pale skin/conjunctiva", "Shortness of breath on exertion",
                     "Dizziness", "Cold hands and feet", "Headache", "Brittle nails", "Pica (craving non-food items)"],
        "complications": ["Heart failure (severe)", "Complications in pregnancy", "Impaired cognitive development in children"],
        "treatment": "Iron supplements + Vitamin C. B12 injections if needed. Treat underlying cause.",
        "prevention": ["Iron-rich diet (green leafy veg, lentils, meat)", "Vitamin C with iron sources",
                       "Deworming", "Iron-folic acid supplementation in pregnancy", "Fortified foods"],
        "incubation_days": "Chronic — develops gradually", "contagious": False,
        "govt_helpline": "Anaemia Mukt Bharat: 1800-180-1104",
    },
    "arthritis": {
        "full_name": "Arthritis", "category": "Musculoskeletal", "icd_code": "M06",
        "description": "Joint inflammation causing pain and stiffness. Osteoarthritis and Rheumatoid Arthritis most common in India.",
        "causes": ["Age-related wear (OA)", "Autoimmune (RA)", "Gout (uric acid)", "Injury",
                   "Obesity", "Genetic factors", "Infections"],
        "symptoms": ["Joint pain", "Swelling and warmth", "Morning stiffness (>1 hour in RA)", "Reduced range of motion",
                     "Redness", "Fatigue", "Fever (in RA)", "Joint deformity (advanced)"],
        "complications": ["Joint deformity", "Disability", "Cardiovascular risk (RA)", "Reduced quality of life"],
        "treatment": "NSAIDs, DMARDs (Methotrexate for RA), physiotherapy, weight loss. Surgery in severe OA.",
        "prevention": ["Maintain healthy weight", "Regular low-impact exercise", "Joint protection techniques",
                       "Calcium and Vitamin D intake", "Early treatment"],
        "incubation_days": "Chronic", "contagious": False,
        "govt_helpline": "NPCDCS: 1800-11-4000",
    },
    "common_cold": {
        "full_name": "Common Cold (Upper Respiratory Infection)", "category": "Viral Respiratory", "icd_code": "J00",
        "description": "Self-limiting viral infection of upper respiratory tract. Over 200 virus strains. Most common illness in India.",
        "causes": ["Rhinovirus (50%)", "Coronavirus", "RSV", "Adenovirus", "Cold/dry air exposure",
                   "Close contact with infected person"],
        "symptoms": ["Runny nose", "Sneezing", "Sore throat", "Nasal congestion", "Low-grade fever",
                     "Mild headache", "Mild body ache", "Watery eyes", "Cough"],
        "complications": ["Secondary bacterial sinusitis", "Ear infection", "Exacerbation of asthma"],
        "treatment": "Symptomatic: rest, fluids, saline nasal drops, paracetamol, steam inhalation. No antibiotics.",
        "prevention": ["Hand washing", "Avoid touching face", "Avoid close contact with infected persons",
                       "Adequate sleep and nutrition"],
        "incubation_days": "1–3 days", "contagious": True,
        "govt_helpline": "General health helpline: 104",
    },
}

SPECIALIST_DIRECTORY = {
    "General Physician":     {"role": "First point of contact for most illnesses", "when_to_visit": "Fever, cold, body pain, general checkup", "avg_fee_inr": 300},
    "Cardiologist":          {"role": "Heart and blood vessel specialist", "when_to_visit": "Chest pain, BP issues, palpitations, heart disease", "avg_fee_inr": 800},
    "Pulmonologist":         {"role": "Lung and respiratory specialist", "when_to_visit": "Persistent cough, breathlessness, TB, asthma", "avg_fee_inr": 700},
    "Gastroenterologist":    {"role": "Digestive system specialist", "when_to_visit": "Abdominal pain, jaundice, diarrhea, hepatitis", "avg_fee_inr": 750},
    "Neurologist":           {"role": "Brain and nervous system specialist", "when_to_visit": "Headache, seizures, stroke symptoms, numbness", "avg_fee_inr": 900},
    "Endocrinologist":       {"role": "Hormonal disorder specialist", "when_to_visit": "Diabetes, thyroid, PCOS, hormonal imbalance", "avg_fee_inr": 800},
    "Orthopaedician":        {"role": "Bone and joint specialist", "when_to_visit": "Fractures, joint pain, arthritis, back pain", "avg_fee_inr": 600},
    "Dermatologist":         {"role": "Skin specialist", "when_to_visit": "Rash, skin infection, allergy, hair loss", "avg_fee_inr": 500},
    "Ophthalmologist":       {"role": "Eye specialist", "when_to_visit": "Eye infection, vision problems, conjunctivitis", "avg_fee_inr": 400},
    "Psychiatrist":          {"role": "Mental health specialist", "when_to_visit": "Depression, anxiety, psychosis, suicidal thoughts", "avg_fee_inr": 1000},
    "Haematologist":         {"role": "Blood disorder specialist", "when_to_visit": "Anaemia, bleeding disorders, blood cancers", "avg_fee_inr": 800},
    "Infectious Disease Specialist": {"role": "Specialist for complex infections", "when_to_visit": "TB, HIV, dengue complications, fever of unknown origin", "avg_fee_inr": 900},
}

GOVT_SCHEMES = [
    {"name": "Ayushman Bharat PM-JAY", "benefit": "₹5 lakh annual health cover per family", "eligibility": "Bottom 40% of population by SECC data", "website": "pmjay.gov.in", "helpline": "14555"},
    {"name": "Pradhan Mantri Swasthya Suraksha Yojana", "benefit": "AIIMS-level hospitals in underserved states", "eligibility": "All Indians", "website": "pmssy-mohfw.nic.in", "helpline": "1800-11-4000"},
    {"name": "Rashtriya Swasthya Bima Yojana", "benefit": "₹30,000 health insurance for BPL families", "eligibility": "BPL card holders", "website": "rsby.gov.in", "helpline": "011-23386246"},
    {"name": "Janani Suraksha Yojana", "benefit": "Cash incentive for institutional delivery", "eligibility": "Pregnant women in low-income families", "website": "nhp.gov.in/jsy", "helpline": "104"},
    {"name": "Nikshay Poshan Yojana", "benefit": "₹500/month nutritional support for TB patients", "eligibility": "All notified TB patients", "website": "nikshay.in", "helpline": "1800-11-6666"},
    {"name": "National Programme for NCD Control", "benefit": "Free screening and treatment for diabetes/BP/cancer", "eligibility": "All adults 30+ years", "website": "mohfw.gov.in", "helpline": "1800-11-4000"},
    {"name": "Mission Indradhanush", "benefit": "Free vaccination for children and pregnant women", "eligibility": "Children 0-2 years, pregnant women", "website": "mohfw.gov.in/mission-indradhanush", "helpline": "1800-11-4449"},
    {"name": "Anaemia Mukt Bharat", "benefit": "Free iron-folic acid supplements and deworming", "eligibility": "Children 6 months–19 years, women, pregnant women", "website": "anemiamuktbharat.info", "helpline": "1800-180-1104"},
    {"name": "Ayushman Arogya Mandir (HWC)", "benefit": "Free comprehensive primary care at Health and Wellness Centres", "eligibility": "All Indians (especially rural)", "website": "ab-hwc.nhp.gov.in", "helpline": "104"},
    {"name": "PM Poshan (Mid-Day Meal)", "benefit": "Free nutritious meals for school children", "eligibility": "Students in government schools classes 1-8", "website": "pmposhan.edu.in", "helpline": "1800-11-8004"},
]

HOME_REMEDIES = {
    "dengue":        ["Stay well hydrated — 8-10 glasses water/day", "Papaya leaf juice (1-2 spoons twice daily) may help platelet count", "Rest completely — avoid physical exertion", "Eat easy-to-digest foods like khichdi and curd rice", "Apply cold compress for high fever"],
    "malaria":       ["Stay hydrated with ORS and coconut water", "Neem leaf decoction — traditional antimalarial support", "Eat small frequent meals — easy to digest", "Use mosquito nets at all times", "Keep fever down with cool damp cloth on forehead"],
    "typhoid":       ["Drink only boiled or bottled water", "Eat soft, easily digestible foods (khichdi, banana, curd)", "Stay hydrated — soups and coconut water", "Complete bed rest", "Garlic has mild antimicrobial properties — add to food"],
    "pneumonia":     ["Steam inhalation 2-3 times daily to loosen phlegm", "Honey and ginger tea for cough relief", "Turmeric milk (haldi doodh) — anti-inflammatory", "Sleep with head slightly elevated", "Stay hydrated with warm fluids"],
    "tuberculosis":  ["High-protein diet essential — eggs, dal, milk, fish", "Vitamin D from sunlight — 20 min/day", "Maintain strict medication adherence", "Plenty of fresh air and ventilation", "Avoid alcohol and smoking completely"],
    "diabetes":      ["Bitter gourd (karela) juice on empty stomach may lower blood sugar", "Fenugreek (methi) seeds soaked overnight in water", "Cinnamon — small amounts in food", "Daily 30-minute brisk walk", "Replace white rice with brown rice or millets"],
    "hypertension":  ["DASH diet — reduce salt below 5g/day", "Garlic daily (anti-hypertensive effect)", "Hibiscus tea may lower BP", "Daily meditation/pranayama 15 minutes", "Reduce caffeine and alcohol"],
    "covid19":       ["Steam inhalation with menthol/eucalyptus 2x/day", "Gargle with warm salt water for sore throat", "Kadha (ginger, tulsi, black pepper, cinnamon decoction)", "Vitamin C-rich foods — amla, guava, citrus", "Monitor oxygen saturation — seek help if SpO2 <94%"],
    "cholera":       ["ORS is life-saving — make at home: 1L water + 6 tsp sugar + 1/2 tsp salt", "Coconut water for electrolyte replacement", "Banana and rice to firm stools", "Zinc supplement (10-20mg/day) reduces duration", "Only boiled water — no raw food"],
    "anaemia":       ["Eat iron-rich foods daily — spinach, drumstick leaves, lentils, dates", "Have Vitamin C with iron sources (lemon on dal)", "Soak 5 figs and 10 raisins overnight — eat in morning", "Avoid tea/coffee with meals (reduce iron absorption)", "Cook in iron vessels — adds dietary iron"],
    "common_cold":   ["Tulsi-ginger-honey tea 3x/day for relief", "Steam inhalation for nasal congestion", "Turmeric milk at bedtime (anti-inflammatory)", "Garlic 2-3 cloves daily (immune booster)", "Stay hydrated — warm water with lemon and honey"],
    "chickenpox":    ["Apply neem leaves paste on blisters — antibacterial, reduces itch", "Oatmeal bath for itching relief", "Trim nails short and keep clean", "Calamine lotion on itchy areas", "Neem leaves under bedsheet — traditional remedy"],
    "hepatitis":     ["Complete rest — liver needs to recover", "Avoid all alcohol completely", "Papaya and papaya leaf juice — supports liver", "Turmeric in diet (curcumin is hepatoprotective)", "High carbohydrate, low fat diet"],
    "conjunctivitis": ["Rose water eye wash (mild antiseptic)", "Cold compress for allergic; warm for bacterial", "Honey diluted in water as eye drops (traditional)", "Cucumber slices on closed eyes for cooling", "Avoid touching eyes — wash hands frequently"],
    "arthritis":     ["Turmeric and ginger anti-inflammatory tea", "Warm mustard oil massage to joints", "Omega-3 from fish/flaxseed reduces inflammation", "Hot/cold therapy for pain management", "Gentle yoga — Tadasana, Vrikshasana for mobility"],
}

EMERGENCY_SIGNS = {
    "dengue":        ["Severe abdominal pain", "Persistent vomiting", "Bleeding from gums/nose", "Blood in urine/stools", "Extreme fatigue/restlessness"],
    "malaria":       ["Altered consciousness/confusion", "Seizures", "Severe anaemia", "Jaundice", "Signs of shock (cold/clammy skin)"],
    "typhoid":       ["Severe abdominal pain (perforation)", "Confusion or delirium", "Severe dehydration", "Blood in stools", "High fever unresponsive to medication"],
    "pneumonia":     ["Breathing rate >30/min", "SpO2 <92%", "Severe chest pain", "Lips/fingertips turning blue", "Confusion in elderly"],
    "tuberculosis":  ["Coughing large amounts of blood", "Severe breathing difficulty", "Chest pain", "High fever with confusion", "Rapid weight loss with wasting"],
    "diabetes":      ["Blood sugar <70 mg/dL (hypoglycemia): sweating, confusion", "Blood sugar >300 mg/dL", "Diabetic ketoacidosis: fruity breath, vomiting", "Loss of consciousness", "Severe chest pain"],
    "hypertension":  ["Systolic BP >180 mmHg", "Severe headache with vision changes", "Chest pain", "Difficulty speaking", "Facial drooping (stroke signs)"],
    "covid19":       ["SpO2 <94% on pulse oximeter", "Breathing difficulty at rest", "Persistent chest pain", "Confusion or inability to wake", "Bluish lips or face"],
    "cholera":       ["Signs of severe dehydration (no urine >6 hours)", "Rapid weak pulse", "Sunken eyes and hollow cheeks", "Unconsciousness", "Muscle cramps so severe cannot walk"],
    "hepatitis":     ["Deep jaundice with confusion (encephalopathy)", "Severe abdominal swelling", "Vomiting blood", "Loss of consciousness", "Unable to eat for >2 days"],
    "chickenpox":    ["Difficulty breathing", "Rash affecting eyes", "Severe headache with stiff neck", "High fever >104°F not responding to paracetamol", "Bleeding into rash"],
    "conjunctivitis": ["Severe eye pain", "Vision loss", "Photophobia with headache", "Redness extending beyond eye", "Chemical exposure — flush with water immediately"],
    "anaemia":       ["Severe shortness of breath at rest", "Chest pain or palpitations", "Fainting", "Haemoglobin <7 g/dL on test", "Pale/blue-tinged gums"],
    "arthritis":     ["Sudden severe joint pain with redness/warmth (may be septic arthritis)", "Inability to move a limb", "High fever with joint pain", "Trauma to already arthritic joint", "Neurological symptoms"],
    "common_cold":   ["High fever >103°F lasting >3 days", "Severe ear pain", "Stiff neck with fever", "Difficulty swallowing", "Breathing difficulty"],
}

SEASONAL_RISK = {
    1:  ["common_cold", "tuberculosis", "arthritis"],
    2:  ["common_cold", "tuberculosis", "arthritis"],
    3:  ["chickenpox", "conjunctivitis", "common_cold"],
    4:  ["chickenpox", "typhoid", "conjunctivitis"],
    5:  ["typhoid", "chickenpox", "dengue"],
    6:  ["dengue", "malaria", "cholera", "typhoid"],
    7:  ["dengue", "malaria", "cholera", "typhoid", "hepatitis"],
    8:  ["dengue", "malaria", "cholera", "typhoid"],
    9:  ["dengue", "malaria", "hepatitis"],
    10: ["dengue", "malaria", "pneumonia"],
    11: ["pneumonia", "tuberculosis", "common_cold"],
    12: ["pneumonia", "tuberculosis", "common_cold", "arthritis"],
}

DISEASE_DRUG_MAP = {
    "dengue":        ["Paracetamol", "ORS", "Platelet transfusion (if severe)"],
    "malaria":       ["Artemether-Lumefantrine", "Chloroquine", "Primaquine", "Quinine (severe)"],
    "typhoid":       ["Ciprofloxacin", "Azithromycin", "Ceftriaxone"],
    "pneumonia":     ["Amoxicillin", "Azithromycin", "Ceftriaxone", "Levofloxacin"],
    "tuberculosis":  ["Rifampicin", "Isoniazid", "Pyrazinamide", "Ethambutol"],
    "diabetes":      ["Metformin", "Glipizide", "Sitagliptin", "Insulin Glargine"],
    "hypertension":  ["Amlodipine", "Losartan", "Atenolol", "Hydrochlorothiazide"],
    "covid19":       ["Paracetamol", "Ivermectin (debated)", "Dexamethasone (severe)", "Paxlovid"],
    "cholera":       ["ORS", "Doxycycline", "Azithromycin", "IV fluids (Ringer's Lactate)"],
    "hepatitis":     ["Tenofovir (Hep B)", "Entecavir (Hep B)", "Sofosbuvir+Daclatasvir (Hep C)"],
    "chickenpox":    ["Acyclovir", "Paracetamol", "Calamine lotion", "Cetirizine (itching)"],
    "conjunctivitis":["Ciprofloxacin eye drops", "Tobramycin", "Olopatadine (allergic)", "Lubricating eye drops"],
    "anaemia":       ["Ferrous Sulphate", "Folic Acid", "Vitamin B12 injection", "Iron sucrose IV"],
    "arthritis":     ["Ibuprofen", "Naproxen", "Methotrexate (RA)", "Hydroxychloroquine (RA)", "Calcium+Vitamin D"],
    "common_cold":   ["Paracetamol", "Cetirizine", "Pseudoephedrine", "Dextromethorphan (cough)", "Saline nasal spray"],
}

FOOD_AVOID = {
    "diabetes":      ["White rice", "White bread/maida", "Sugary drinks", "Sweets and mithai", "Potato chips", "Processed foods", "Fruit juices (bottled)"],
    "hypertension":  ["Table salt", "Pickles and papads", "Processed meats", "Canned/packaged foods", "Alcohol", "Caffeine (excess)"],
    "typhoid":       ["Raw salads", "Raw fruits with skin", "Street food", "Spicy foods", "Fried foods", "Alcohol", "Milk (unless pasteurised)"],
    "cholera":       ["Raw vegetables", "Raw seafood", "Street food", "Ice (from unknown water)", "Carbonated drinks", "Alcohol"],
    "hepatitis":     ["Alcohol (strictly)", "Fatty/oily foods", "Raw shellfish", "Processed foods", "Red meat (excess)"],
    "anaemia":       ["Tea with meals", "Coffee with meals", "Calcium supplements with iron", "Spinach with dairy (oxalate)"],
    "arthritis":     ["Red meat", "Processed foods", "Sugary beverages", "Purine-rich foods (for gout: organ meats, shellfish)", "Alcohol"],
    "dengue":        ["Spicy foods", "Fried foods", "Caffeinated drinks", "Alcohol", "Dark-coloured foods during platelet monitoring"],
    "tuberculosis":  ["Alcohol", "Tobacco", "Refined sugars", "Foods that interact with Rifampicin", "Raw sprouts (infection risk)"],
    "pneumonia":     ["Cold foods and drinks", "Dairy products (thickens mucus)", "Fried oily foods", "Alcohol"],
}

FOOD_INCLUDE = {
    "diabetes":      ["Brown rice and millets", "Fenugreek seeds", "Bitter gourd (karela)", "Cinnamon", "Green leafy vegetables", "Legumes and lentils", "Amla"],
    "hypertension":  ["Banana (potassium)", "Spinach", "Garlic", "Oats", "Flaxseeds", "Beetroot", "Hibiscus tea", "Low-fat curd"],
    "anaemia":       ["Drumstick leaves (moringa)", "Spinach", "Dates and raisins", "Pomegranate", "Sesame seeds", "Jaggery", "Lentils", "Liver (non-vegetarian)"],
    "typhoid":       ["Boiled rice/khichdi", "Banana", "Boiled potato", "Curd (probiotics)", "Coconut water", "Apple sauce"],
    "tuberculosis":  ["Eggs", "Milk and paneer", "Dal", "Fish", "Banana", "Nuts and seeds", "Vitamin D through sunlight"],
    "hepatitis":     ["Papaya", "Turmeric", "Garlic", "Green tea", "Carrot and beetroot juice", "Oatmeal", "Blueberries"],
    "arthritis":     ["Turmeric (curcumin)", "Ginger", "Omega-3 fish (mackerel/sardines)", "Cherries", "Broccoli", "Walnuts", "Olive oil"],
    "cholera":       ["ORS", "Coconut water", "Banana", "Boiled rice", "Boiled potato", "Yogurt/curd"],
    "dengue":        ["Papaya leaf juice", "Pomegranate juice", "Kiwi", "Spinach", "Coconut water", "Turmeric milk"],
    "pneumonia":     ["Warm turmeric milk", "Honey", "Garlic", "Ginger tea", "Vitamin C foods (amla, citrus)", "Warm soups"],
}
